In [1]:
import requests
import pandas as pd
import time

URL = "https://api.open-meteo.com/v1/forecast"

areas = {
    "RR Nagar": (12.9250, 77.5190),
    "Indiranagar": (12.9784, 77.6408),
    "Hebbal": (13.0358, 77.5970),
    "Electronic City": (12.8452, 77.6602),
    "Whitefield": (12.9698, 77.7499)
}

all_weather = []

for area, (latitude, longitude) in areas.items():

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": "temperature_2m,relative_humidity_2m,precipitation",
        "timezone": "Asia/Kolkata",
        "forecast_days": 7
    }

    try:
        r = requests.get(URL, params=params, timeout=20)
        r.raise_for_status()

        result = r.json()

        wx = pd.DataFrame(result["hourly"])


        wx["time"] = pd.to_datetime(wx["time"])
        wx["area"] = area

        
        all_weather.append(wx)

        print(area, ":", len(wx), "records")

    except Exception as e:
        print("Error for", area, ":", e)

   
    time.sleep(1)


weather_df = pd.concat(all_weather, ignore_index=True)


weather_df.to_csv("bengaluru_weather.csv", index=False)

print("Total records:", len(weather_df))
print("CSV saved as bengaluru_weather.csv")

weather_df.head()

RR Nagar : 168 records
Indiranagar : 168 records
Hebbal : 168 records
Electronic City : 168 records
Whitefield : 168 records
Total records: 840
CSV saved as bengaluru_weather.csv

,time,temperature_2m,relative_humidity_2m,precipitation,area
0,2026-08-19 00:00:00,21.9,95,0.0,RR Nagar
1,2026-08-19 01:00:00,21.9,93,0.0,RR Nagar
2,2026-08-19 02:00:00,21.4,94,0.0,RR Nagar
3,2026-08-19 03:00:00,21.4,92,0.0,RR Nagar
4,2026-08-19 04:00:00,21.4,90,0.0,RR Nagar

In [3]:
import requests
import pandas as pd
import time

URL = "https://air-quality-api.open-meteo.com/v1/air-quality"

areas = {
    "RR Nagar": (12.9250, 77.5190),
    "Indiranagar": (12.9784, 77.6408),
    "Hebbal": (13.0358, 77.5970),
    "Electronic City": (12.8452, 77.6602),
    "Whitefield": (12.9698, 77.7499)
}

all_air_quality = []

for area, (latitude, longitude) in areas.items():

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": "pm2_5,pm10,carbon_monoxide",
        "timezone": "Asia/Kolkata",
        "forecast_days": 7
    }

    try:
        r = requests.get(URL, params=params, timeout=20)
        r.raise_for_status()

        result = r.json()

        aq = pd.DataFrame(result["hourly"])
   
        aq["time"] = pd.to_datetime(aq["time"])
 
        aq["area"] = area
        all_air_quality.append(aq)

        print(area, ":", len(aq), "records")

    except Exception as e:
        print("Error for", area, ":", e)

  
    time.sleep(1)


air_quality_df = pd.concat(all_air_quality, ignore_index=True)

air_quality_df.to_csv("bengaluru_air_quality.csv", index=False)

print("Total records:", len(air_quality_df))
print("CSV saved as bengaluru_air_quality.csv")

air_quality_df.head()

RR Nagar : 168 records
Indiranagar : 168 records
Hebbal : 168 records
Electronic City : 168 records
Whitefield : 168 records
Total records: 840
CSV saved as bengaluru_air_quality.csv

                 time  pm2_5  pm10  carbon_monoxide      area
0 2026-08-19 00:00:00    9.2  12.2            247.0  RR Nagar
1 2026-08-19 01:00:00    7.7  10.3            195.0  RR Nagar
2 2026-08-19 02:00:00    6.6   8.8            158.0  RR Nagar
3 2026-08-19 03:00:00    5.7   7.5            145.0  RR Nagar
4 2026-08-19 04:00:00    5.2   6.8            147.0  RR Nagar

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

URL = "https://books.toscrape.com/catalogue/page-{}.html"

all_books = []

for page in range(1, 51):

    try:
        url = URL.format(page)

        r = requests.get(url, timeout=20)
        r.raise_for_status()

        soup = BeautifulSoup(r.text, "html.parser")

        books = soup.select("article.product_pod")

        for book in books:

            # Extract title
            title = book.h3.a["title"]

            # Extract price
            price = book.select_one(".price_color").text.strip()

            # Extract rating
            rating = book.select_one("p.star-rating")["class"][1]

            all_books.append({
                "title": title,
                "price": price,
                "rating": rating
            })

        print("Page", page, ":", len(books), "books")

    except Exception as e:
        print("Error on page", page, ":", e)

    time.sleep(1)

# Convert to DataFrame
books_df = pd.DataFrame(all_books)

# Save as CSV
books_df.to_csv("books_data.csv", index=False)

print("Total books:", len(books_df))
print("CSV saved as books_data.csv")

books_df.head()

Page 1 : 20 books
Page 2 : 20 books
Page 3 : 20 books
Page 4 : 20 books
Page 5 : 20 books
Page 6 : 20 books
Page 7 : 20 books
Page 8 : 20 books
Page 9 : 20 books
Page 10 : 20 books
Page 11 : 20 books
Page 12 : 20 books
Page 13 : 20 books
Page 14 : 20 books
Page 15 : 20 books
Page 16 : 20 books
Page 17 : 20 books
Page 18 : 20 books
Page 19 : 20 books
Page 20 : 20 books
Page 21 : 20 books
Page 22 : 20 books
Page 23 : 20 books
Page 24 : 20 books
Page 25 : 20 books
Page 26 : 20 books
Page 27 : 20 books
Page 28 : 20 books
Page 29 : 20 books
Page 30 : 20 books
Page 31 : 20 books
Page 32 : 20 books
Page 33 : 20 books
Page 34 : 20 books
Page 35 : 20 books
Page 36 : 20 books
Page 37 : 20 books
Page 38 : 20 books
Page 39 : 20 books
Page 40 : 20 books
Page 41 : 20 books
Page 42 : 20 books
Page 43 : 20 books
Page 44 : 20 books
Page 45 : 20 books
Page 46 : 20 books
Page 47 : 20 books
Page 48 : 20 books
Page 49 : 20 books
Page 50 : 20 books
Total books: 1000
CSV saved as books_data.csv

                                   title    price rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five