In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from scipy.stats import zscore
from scipy import stats

In [2]:
df=pd.read_csv("Automobile.csv")

In [3]:
df

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8.0,307.0,130.0,3504.0,12.0,70,usa
1,buick skylark 320,15.0,8.0,350.0,165.0,3693.0,11.5,70,usa
2,plymouth satellite,18.0,8.0,318.0,150.0,3436.0,11.0,70,usa
3,amc rebel sst,16.0,8.0,304.0,150.0,3433.0,12.0,70,usa
4,ford torino,17.0,NaN,302.0,140.0,3449.0,10.5,70,usa
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4.0,140.0,86.0,2790.0,15.6,82,usa
394,vw pickup,44.0,4.0,97.0,52.0,2130.0,24.6,82,europe
395,dodge rampage,32.0,4.0,135.0,84.0,2295.0,11.6,82,usa
396,ford ranger,28.0,4.0,120.0,79.0,2625.0,18.6,82,usa
397,chevy s-10,31.0,4.0,119.0,82.0,2720.0,19.4,82,usa

In [7]:
df.head(10)

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8.0,307.0,130.0,3504.0,12.0,70,usa
1,buick skylark 320,15.0,8.0,350.0,165.0,3693.0,11.5,70,usa
2,plymouth satellite,18.0,8.0,318.0,150.0,3436.0,11.0,70,usa
3,amc rebel sst,16.0,8.0,304.0,150.0,3433.0,12.0,70,usa
4,ford torino,17.0,NaN,302.0,140.0,3449.0,10.5,70,usa
5,ford galaxie 500,15.0,8.0,429.0,198.0,4341.0,10.0,70,usa
6,chevrolet impala,14.0,8.0,454.0,220.0,NaN,9.0,70,usa
7,plymouth fury iii,14.0,8.0,440.0,215.0,4312.0,8.5,70,usa
8,pontiac catalina,14.0,8.0,455.0,NaN,4425.0,10.0,70,usa
9,amc ambassador dpl,15.0,8.0,390.0,190.0,3850.0,8.5,70,usa

In [6]:
df.shape

(398, 9)

In [13]:
df.columns
df.dtypes

name             object
mpg             float64
cylinders       float64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [15]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,395.000000,395.000000,386.000000,396.000000,395.000000,398.000000
mean,23.514573,5.445570,193.340506,104.316062,2965.025253,15.562278,76.010050
std,7.815984,1.696203,104.425993,38.086281,845.254458,2.750260,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,102.500000,75.250000,2222.250000,13.850000,73.000000
50%,23.000000,4.000000,146.000000,92.500000,2797.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,125.000000,3581.750000,17.150000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [27]:
category=df.select_dtypes("number").columns
category

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year'],
      dtype='object')

In [38]:
numeric=df.select_dtypes("object").columns

In [21]:
df.columns.unique()

Index(['name', 'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin'],
      dtype='object')

In [36]:
for col in category:
    print(f"{col}")
    print(df[col].unique())
    print()

mpg
[18.  15.  16.  17.  14.  24.  22.  21.  27.  26.  25.  10.  11.   9.
 28.  19.  12.  13.  23.  30.  31.  35.  20.  29.  32.  33.  17.5 15.5
 14.5 22.5 24.5 18.5 29.5 26.5 16.5 31.5 36.  25.5 33.5 20.5 30.5 21.5
 43.1 36.1 32.8 39.4 19.9 19.4 20.2 19.2 25.1 20.6 20.8 18.6 18.1 17.7
 27.5 27.2 30.9 21.1 23.2 23.8 23.9 20.3 21.6 16.2 19.8 22.3 17.6 18.2
 16.9 31.9 34.1 35.7 27.4 25.4 34.2 34.5 31.8 37.3 28.4 28.8 26.8 41.5
 38.1 32.1 37.2 26.4 24.3 19.1 34.3 29.8 31.3 37.  32.2 46.6 27.9 40.8
 44.3 43.4 36.4 44.6 40.9 33.8 32.7 23.7 23.6 32.4 26.6 25.8 23.5 39.1
 39.  35.1 32.3 37.7 34.7 34.4 29.9 33.7 32.9 31.6 28.1 30.7 24.2 22.4
 34.  38.  44. ]

cylinders
[ 8. nan  4.  6.  3.  5.]

displacement
[307.  350.  318.  304.  302.  429.  454.  440.  455.  390.  383.  340.
 400.  113.  198.  199.  200.   97.  110.  107.  104.  121.  360.  140.
  98.  232.  225.  250.  351.  258.  122.  116.   79.   88.   71.   72.
  91.   97.5  70.  120.   96.  108.  155.   68.  114.  156.   76.   83.
  90.  231.  262.  134.  119.  171.  115.  101.  305.   85.  130.  168.
 111.  260.  151.  146.   80.   78.    nan 105.  131.  163.   89.  267.
  86.  183.  141.  173.  135.   81.  100.  145.  112.  181.  144. ]

horsepower
[130. 165. 150. 140. 198. 220. 215.  nan 190. 170. 160. 225.  95.  97.
  85.  88.  87.  90. 113. 200. 210. 193. 100. 105. 175. 153. 180. 110.
  72.  86.  70.  76.  65.  69.  60.  80.  54. 208. 155. 112.  92. 145.
 137. 158.  46. 167.  94. 107. 230.  49.  75.  91. 122.  67.  83.  78.
  52.  61.  93. 148. 129.  96.  71.  98. 115.  53.  81.  79. 120. 152.
 102. 108.  68.  58. 149.  89.  63.  48.  66. 139. 103. 125. 133. 138.
 135. 142.  77.  62. 132.  84.  64.  74. 116.  82.]

weight
[3504. 3693. 3436. 3433. 3449. 4341.   nan 4312. 4425. 3850. 3563. 3609.
 3761. 3086. 2372. 2833. 2774. 2587. 2130. 1835. 2672. 2430. 2375. 2234.
 2648. 4615. 4376. 4382. 4732. 2264. 2228. 2046. 2634. 3439. 3329. 3302.
 3288. 4209. 4464. 4154. 4096. 4955. 4746. 5140. 2962. 2408. 3282. 3139.
 2220. 2123. 2074. 2065. 1773. 1613. 1834. 1955. 2278. 2126. 2254. 2226.
 4274. 4385. 4135. 4129. 3672. 4633. 4502. 4456. 4422. 2330. 3892. 4098.
 4294. 4077. 2933. 2511. 2979. 2189. 2395. 2288. 2506. 2164. 2100. 4100.
 3988. 4042. 3777. 4952. 4363. 4237. 4735. 4951. 3821. 3121. 3278. 2945.
 3021. 2904. 1950. 4997. 4906. 4654. 4499. 2789. 2279. 2401. 2379. 2124.
 2310. 2472. 2265. 4082. 4278. 1867. 2158. 2582. 2868. 3399. 2660. 2807.
 3664. 3102. 2875. 2901. 3336. 2451. 1836. 2542. 3781. 3632. 3613. 4141.
 4699. 4457. 4638. 4257. 2219. 1963. 2300. 1649. 2003. 2125. 2108. 2246.
 2489. 2391. 2000. 3264. 3459. 3432. 3158. 4668. 4440. 4498. 4657. 3907.
 3897. 3730. 3785. 3039. 3221. 3169. 2171. 2639. 2914. 2592. 2702. 2223.
 2545. 2984. 1937. 3211. 2694. 2957. 2671. 1795. 2464. 2572. 2255. 2202.
 4215. 4190. 3962. 3233. 3353. 3012. 3085. 2035. 3651. 3574. 3645. 3193.
 1825. 1990. 2155. 2565. 3150. 3940. 3270. 2930. 3820. 4380. 4055. 3870.
 3755. 2045. 1945. 3880. 4060. 4140. 4295. 3520. 3425. 3630. 3525. 4220.
 4165. 4325. 4335. 1940. 2740. 2755. 2051. 2075. 1985. 2190. 2815. 2600.
 2720. 1800. 2070. 3365. 3735. 3570. 3535. 3155. 2965. 3430. 3210. 3380.
 3070. 3620. 3410. 3445. 3205. 4080. 2560. 2230. 2515. 2745. 2855. 2405.
 2830. 3140. 2795. 2135. 3245. 2990. 2890. 3265. 3360. 3840. 3955. 3830.
 4360. 4054. 3605. 1925. 1975. 1915. 2670. 3530. 3900. 3190. 3420. 2200.
 2150. 2020. 2595. 2700. 2556. 2144. 1968. 2120. 2019. 2678. 2870. 3003.
 3381. 2188. 2711. 2434. 2110. 2800. 2085. 2335. 2950. 3250. 1850. 2145.
 1845. 2910. 2420. 2500. 2905. 2290. 2490. 2635. 2620. 2725. 2385. 1755.
 1875. 1760. 2050. 2215. 2380. 2320. 2210. 2350. 2615. 3230. 3160. 2900.
 3415. 3725. 3060. 3465. 2605. 2640. 2575. 2525. 2735. 2865. 3035. 1980.
 2025. 1970. 2160. 2205. 2245. 1965. 1995. 3015. 2585. 2835. 2665. 2370.
 2790. 2295. 2625.]

acceleration
[12.  11.5 11.  10.5 10.   9.   8.5  8.   9.5 15.   nan 15.5 16.  14.5
 20.5 17.5 14.  13.5 18.5 19.  13.  19.5 18.  17.  23.5 16.5 12.5 21.
 16.9 14.9 17.7 15.3 13.9 12.8 15.4 17.6 22.2 22.1 14.2 17.4 16.2 17.8
 12.2 16.4 13.6 15.7 13.2 21.9 16.7 12.1 14.8 18.6 16.8 13.7 11.1 11.4
 18.2 15.8 15.9 14.1 21.5 14.4 19.4 19.2 17.2 18.7 15.1 13.4 11.2 14.7
 16.6 17.3 15.2 14.3 20.1 24.8 11.3 12.9 18.8 18.1 17.9 21.7 23.7 19.9
 21.8 13.8 12.6 16.1 20.7 18.3 20.4 19.6 17.1 15.6 24.6 11.6]

model_year
[70 71 72 73 74 75 76 77 78 79 80 81 82]

In [37]:
df.isnull().sum()

name             0
mpg              0
cylinders        3
displacement     3
horsepower      12
weight           2
acceleration     3
model_year       0
origin           0
dtype: int64

In [39]:
for col in numerical_columns:
    df[col] = df[col].fillna(df[col].median())

In [41]:
for col in category:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [42]:
df.isnull().sum()

name            0
mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df = df.drop_duplicates()

In [46]:
df["horsepower"] = df["horsepower"].replace("?", np.nan)
df["horsepower"] = pd.to_numeric(df["horsepower"])
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].median())

print(df["horsepower"].head())

0    130.0
1    165.0
2    150.0
3    150.0
4    140.0
Name: horsepower, dtype: float64

In [49]:

df["origin"] = df["origin"].map({
    1: "usa",
    2: "europe",
    3: "japan"
})
print(df["origin"].unique())

[nan]

In [50]:
df["weight_kg"] = df["weight"] * 0.453592

In [51]:
df["mpg_category"] = "Medium"
df.loc[df["mpg"] < 20, "mpg_category"] = "Low"
df.loc[df["mpg"] >= 30, "mpg_category"] = "High"

print(df[["mpg", "mpg_category"]].head())

    mpg mpg_category
0  18.0          Low
1  15.0          Low
2  18.0          Low
3  16.0          Low
4  17.0          Low

In [52]:
df["vehicle_age"] = 2026 - df["model_year"]

In [53]:
df.rename(columns={
    "mpg": "miles_per_gallon",
    "horsepower": "hp",
    "weight": "weight_lbs",
    "model_year": "year"
}, inplace=True)

print(df.columns)

Index(['name', 'miles_per_gallon', 'cylinders', 'displacement', 'hp',
       'weight_lbs', 'acceleration', 'year', 'origin', 'weight_kg',
       'mpg_category', 'vehicle_age'],
      dtype='object')

In [57]:
print("MPG > 30")
print(df[df["miles_per_gallon"] > 30])

print("Horsepower > 150")
print(df[df["hp"] > 150])

print("Cylinders >= 6")
print(df[df["cylinders"] >= 6])

print("After 1980")
print(df[df["year"] > 1980])

print("USA vehicles")
print(df[df["origin"] == "usa"])

MPG > 30
                    name  miles_per_gallon  cylinders  displacement    hp  \
53   toyota corolla 1200              31.0        4.0          71.0  65.0
54           datsun 1200              35.0        4.0          72.0  69.0
129          datsun b210              31.0        4.0          79.0  67.0
131  toyota corolla 1200              32.0        4.0          71.0  92.5
144        toyota corona              31.0        4.0          76.0  52.0
..                   ...               ...        ...           ...   ...
390     toyota celica gt              32.0        4.0         144.0  96.0
391    dodge charger 2.2              36.0        4.0         135.0  84.0
394            vw pickup              44.0        4.0          97.0  52.0
395        dodge rampage              32.0        4.0         135.0  84.0
397           chevy s-10              31.0        4.0         119.0  82.0

     weight_lbs  acceleration  year origin    weight_kg mpg_category  \
53       1773.0          19.0    71    NaN   804.218616         High
54       1613.0          18.0    71    NaN   731.643896         High
129      1950.0          19.0    74    NaN   884.504400         High
131      1836.0          15.5    74    NaN   832.794912         High
144      1649.0          16.5    74    NaN   747.973208         High
..          ...           ...   ...    ...          ...          ...
390      2665.0          13.9    82    NaN  1208.822680         High
391      2370.0          13.0    82    NaN  1075.013040         High
394      2130.0          24.6    82    NaN   966.150960         High
395      2295.0          11.6    82    NaN  1040.993640         High
397      2720.0          19.4    82    NaN  1233.770240         High

     vehicle_age
53          1955
54          1955
129         1952
131         1952
144         1952
..           ...
390         1944
391         1944
394         1944
395         1944
397         1944

[85 rows x 12 columns]
Horsepower > 150
                                name  miles_per_gallon  cylinders  \
1                  buick skylark 320              15.0        8.0
5                   ford galaxie 500              15.0        8.0
6                   chevrolet impala              14.0        8.0
7                  plymouth fury iii              14.0        8.0
9                 amc ambassador dpl              15.0        8.0
10               dodge challenger se              15.0        8.0
11                plymouth 'cuda 340              14.0        8.0
13           buick estate wagon (sw)              14.0        8.0
25                         ford f250              10.0        8.0
26                         chevy c20              10.0        8.0
27                        dodge d200              11.0        8.0
28                          hi 1200d               9.0        8.0
38                  chevrolet impala              14.0        8.0
39         pontiac catalina brougham              14.0        8.0
40                  ford galaxie 500              14.0        8.0
42                 dodge monaco (sw)              12.0        8.0
43          ford country squire (sw)              13.0        8.0
44               pontiac safari (sw)              13.0        8.0
62                  chevrolet impala              13.0        8.0
63                  pontiac catalina              14.0        8.0
65                  ford galaxie 500              14.0        8.0
67                   mercury marquis              11.0        8.0
68              buick lesabre custom              13.0        8.0
69        oldsmobile delta 88 royale              12.0        8.0
70            chrysler newport royal              13.0        8.0
85                 buick century 350              13.0        8.0
90          mercury marquis brougham              12.0        8.0
92                          ford ltd              13.0        8.0
94      chrysler new yorker brougham              13.0        8.0
95          buick electra 225 custom              12.0        8.0
96           amc ambassador brougham              13.0        8.0
104                     ford country              12.0        8.0
105           plymouth custom suburb              13.0        8.0
106         oldsmobile vista cruiser              12.0        8.0
116               pontiac grand prix              16.0        8.0
124                 oldsmobile omega              11.0        8.0
156                 pontiac catalina              16.0        8.0
190                 ford gran torino              14.5        8.0
212                 cadillac seville              16.5        8.0
229            pontiac grand prix lj              16.0        8.0
230     chevrolet monte carlo landau              15.5        8.0
231                 chrysler cordoba              15.5        8.0
263  buick regal sport coupe (turbo)              17.7        6.0
289          buick estate wagon (sw)              16.9        8.0

     displacement     hp  weight_lbs  acceleration  year origin    weight_kg  \
1           350.0  165.0      3693.0          11.5    70    NaN  1675.115256
5           429.0  198.0      4341.0          10.0    70    NaN  1969.042872
6           454.0  220.0      2797.5           9.0    70    NaN  1268.923620
7           440.0  215.0      4312.0           8.5    70    NaN  1955.888704
9           390.0  190.0      3850.0           8.5    70    NaN  1746.329200
10          383.0  170.0      3563.0          10.0    70    NaN  1616.148296
11          340.0  160.0      3609.0           8.0    70    NaN  1637.013528
13          455.0  225.0      3086.0          10.0    70    NaN  1399.784912
25          360.0  215.0      4615.0          14.0    70    NaN  2093.327080
26          307.0  200.0      4376.0          15.0    70    NaN  1984.918592
27          318.0  210.0      4382.0          13.5    70    NaN  1987.640144
28          304.0  193.0      4732.0          18.5    70    NaN  2146.397344
38          350.0  165.0      4209.0          12.0    71    NaN  1909.168728
39          400.0  175.0      4464.0          11.5    71    NaN  2024.834688
40          351.0  153.0      4154.0          13.5    71    NaN  1884.221168
42          383.0  180.0      4955.0          11.5    71    NaN  2247.548360
43          400.0  170.0      4746.0          12.0    71    NaN  2152.747632
44          400.0  175.0      5140.0          12.0    71    NaN  2331.462880
62          350.0  165.0      4274.0          12.0    72    NaN  1938.652208
63          400.0  175.0      4385.0          12.0    72    NaN  1989.000920
65          351.0  153.0      4129.0          13.0    72    NaN  1872.881368
67          429.0  208.0      4633.0          11.0    72    NaN  2101.491736
68          350.0  155.0      4502.0          13.5    72    NaN  2042.071184
69          350.0  160.0      4456.0          13.5    72    NaN  2021.205952
70          400.0  190.0      4422.0          12.5    72    NaN  2005.783824
85          350.0  175.0      4100.0          13.0    73    NaN  1859.727200
90          429.0  198.0      4952.0          11.5    73    NaN  2246.187584
92          351.0  158.0      4363.0          13.0    73    NaN  1979.021896
94          440.0  215.0      4735.0          11.0    73    NaN  2147.758120
95          455.0  225.0      4951.0          11.0    73    NaN  2245.733992
96          360.0  175.0      3821.0          11.0    73    NaN  1733.175032
104         400.0  167.0      4906.0          12.5    73    NaN  2225.322352
105         360.0  170.0      4654.0          13.0    73    NaN  2111.017168
106         350.0  180.0      4499.0          12.5    73    NaN  2040.710408
116         400.0  230.0      4278.0           9.5    73    NaN  1940.466576
124         350.0  180.0      3664.0          11.0    73    NaN  1661.961088
156         400.0  170.0      4668.0          11.5    75    NaN  2117.367456
190         351.0  152.0      4215.0          12.8    76    NaN  1911.890280
212         350.0  180.0      4380.0          12.1    76    NaN  1986.732960
229         400.0  180.0      4220.0          11.1    77    NaN  1914.158240
230         350.0  170.0      4165.0          11.4    77    NaN  1889.210680
231         400.0  190.0      4325.0          12.2    77    NaN  1961.785400
263         231.0  165.0      3445.0          13.4    78    NaN  1562.624440
289         350.0  155.0      4360.0          14.9    79    NaN  1977.661120

    mpg_category  vehicle_age
1            Low         1956
5            Low         1956
6            Low         1956
7            Low         1956
9            Low         1956
10           Low         1956
11           Low         1956
13           Low         1956
25           Low         1956
26           Low         1956
27           Low         1956
28           Low         1956
38           Low         1955
39           Low         1955
40           Low         1955
42           Low         1955
43           Low         1955
44           Low         1955
62           Low         1954
63           Low         1954
65           Low         1954
67           Low         1954
68           Low         1954
69           Low         1954
70           Low         1954
85           Low         1953
90           Low         1953
92           Low         1953
94           Low         1953
95           Low         1953
96           Low         1953
104          Low         1953
105          Low         1953
106          Low         1953
116          Low         1953
124          Low         1953
156          Low         1951
190          Low         1950
212          Low         1950
229          Low         1949
230          Low         1949
231          Low         1949
263          Low         1948
289          Low         1947
Cylinders >= 6
                                  name  miles_per_gallon  cylinders  \
0            chevrolet chevelle malibu              18.0        8.0
1                    buick skylark 320              15.0        8.0
2                   plymouth satellite              18.0        8.0
3                        amc rebel sst              16.0        8.0
5                     ford galaxie 500              15.0        8.0
..                                 ...               ...        ...
365                    ford granada gl              20.2        6.0
366             chrysler lebaron salon              17.6        6.0
386              buick century limited              25.0        6.0
387  oldsmobile cutlass ciera (diesel)              38.0        6.0
389                     ford granada l              22.0        6.0

     displacement     hp  weight_lbs  acceleration  year origin    weight_kg  \
0           307.0  130.0      3504.0          12.0    70    NaN  1589.386368
1           350.0  165.0      3693.0          11.5    70    NaN  1675.115256
2           318.0  150.0      3436.0          11.0    70    NaN  1558.542112
3           304.0  150.0      3433.0          12.0    70    NaN  1557.181336
5           429.0  198.0      4341.0          10.0    70    NaN  1969.042872
..            ...    ...         ...           ...   ...    ...          ...
365         200.0   88.0      3060.0          17.1    81    NaN  1387.991520
366         225.0   85.0      3465.0          16.6    81    NaN  1571.696280
386         181.0  110.0      2945.0          16.4    82    NaN  1335.828440
387         262.0   85.0      3015.0          17.0    82    NaN  1367.579880
389         232.0  112.0      2835.0          14.7    82    NaN  1285.933320

    mpg_category  vehicle_age
0            Low         1956
1            Low         1956
2            Low         1956
3            Low         1956
5            Low         1956
..           ...          ...
365       Medium         1945
366          Low         1945
386       Medium         1944
387         High         1944
389       Medium         1944

[185 rows x 12 columns]
After 1980
Empty DataFrame
Columns: [name, miles_per_gallon, cylinders, displacement, hp, weight_lbs, acceleration, year, origin, weight_kg, mpg_category, vehicle_age]
Index: []
USA vehicles
Empty DataFrame
Columns: [name, miles_per_gallon, cylinders, displacement, hp, weight_lbs, acceleration, year, origin, weight_kg, mpg_category, vehicle_age]
Index: []